#!/usr/bin/env node
/**
 * VoiceNotes — Railway startup server
 * - Serves static files
 * - Proxies POST /api/lemur → AssemblyAI LeMUR (bypasses browser CORS)
 * - Injects ASSEMBLYAI_KEY into config.js
 */
const http  = require('http');
const https = require('https');
const fs    = require('fs');
const path  = require('path');

const ASSEMBLYAI_KEY = process.env.ASSEMBLYAI_KEY || '';
const PORT = process.env.PORT || '3000';

// Inject API key into config.js
const configContent = `/* Auto-generated by start.js — do not edit */\nwindow.ASSEMBLYAI_KEY = ${JSON.stringify(ASSEMBLYAI_KEY)};\n`;
fs.writeFileSync(path.join(__dirname, 'config.js'), configContent, 'utf8');

if (ASSEMBLYAI_KEY) {
  console.log(`[VoiceNotes] ASSEMBLYAI_KEY injected`);
} else {
  console.warn(`[VoiceNotes] WARNING: ASSEMBLYAI_KEY not set`);
}

const MIME = {
  '.html': 'text/html; charset=utf-8',
  '.css':  'text/css',
  '.js':   'application/javascript',
  '.json': 'application/json',
  '.png':  'image/png',
  '.jpg':  'image/jpeg',
  '.svg':  'image/svg+xml',
  '.ico':  'image/x-icon',
  '.woff': 'font/woff',
  '.woff2':'font/woff2',
};

const server = http.createServer((req, res) => {

  /* ── OPTIONS preflight ── */
  if (req.method === 'OPTIONS') {
    res.writeHead(204, { 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'GET,POST,OPTIONS', 'Access-Control-Allow-Headers': 'Content-Type' });
    res.end();
    return;
  }

  /* ── LeMUR proxy ── */
  if (req.method === 'POST' && req.url === '/api/lemur') {
    let body = '';
    req.on('data', chunk => { body += chunk; });
    req.on('end', () => {
      const opts = {
        hostname: 'api.assemblyai.com',
        path: '/lemur/v3/lemur/task',
        method: 'POST',
        headers: {
          'Authorization': ASSEMBLYAI_KEY,
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(body),
        },
      };
      const pr = https.request(opts, (r) => {
        res.writeHead(r.statusCode, { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' });
        r.pipe(res);
      });
      pr.on('error', (e) => {
        res.writeHead(502, { 'Content-Type': 'application/json' });
        res.end(JSON.stringify({ error: e.message }));
      });
      pr.write(body);
      pr.end();
    });
    return;
  }

  /* ── Static files ── */
  let urlPath = req.url.split('?')[0];
  if (urlPath === '/') urlPath = '/index.html';
  const filePath = path.normalize(path.join(__dirname, urlPath));

  // Prevent path traversal
  if (!filePath.startsWith(path.normalize(__dirname))) {
    res.writeHead(403); res.end('Forbidden'); return;
  }

  fs.readFile(filePath, (err, data) => {
    if (err) { res.writeHead(404); res.end('Not Found'); return; }
    const ext = path.extname(filePath).toLowerCase();
    res.writeHead(200, { 'Content-Type': MIME[ext] || 'application/octet-stream' });
    res.end(data);
  });
});

server.listen(PORT, () => {
  console.log(`[VoiceNotes] Listening on port ${PORT}`);
});

