#!/usr/bin/env node
/**
 * Railway startup script
 * 1. Reads ASSEMBLYAI_KEY from environment variable
 * 2. Writes it into config.js so the browser can pick it up
 * 3. Starts the static file server
 */
const fs    = require('fs');
const path  = require('path');
const { spawn } = require('child_process');

const key  = process.env.ASSEMBLYAI_KEY || '';
const port = process.env.PORT || '3000';

// Write config.js with the injected key
const configContent = `/* Auto-generated by start.js from environment variable — do not edit */\nwindow.ASSEMBLYAI_KEY = ${JSON.stringify(key)};\n`;
fs.writeFileSync(path.join(__dirname, 'config.js'), configContent, 'utf8');

if (key) {
  console.log('[start] ASSEMBLYAI_KEY injected into config.js');
} else {
  console.warn('[start] WARNING: ASSEMBLYAI_KEY environment variable is not set');
}

// Start the static file server
const server = spawn(
  'npx', ['serve', '.', '--listen', port],
  { stdio: 'inherit', shell: true }
);

server.on('exit', (code) => process.exit(code ?? 0));
